module.exports = function (familyClass) {
	switch (familyClass) {
		case 0x0000: return "No Classification";
		case 0x0100: return "Oldstyle Serifs";
		case 0x0101: return "Oldstyle Serifs - IBM Rounded Legibility";
		case 0x0102: return "Oldstyle Serifs - Garalde";
		case 0x0103: return "Oldstyle Serifs - Venetian";
		case 0x0104: return "Oldstyle Serifs - Modified Venetian";
		case 0x0105: return "Oldstyle Serifs - Dutch Modern";
		case 0x0106: return "Oldstyle Serifs - Dutch Traditional";
		case 0x0107: return "Oldstyle Serifs - Contemporary";
		case 0x0108: return "Oldstyle Serifs - Calligraphic";
		case 0x010e: return "Oldstyle Serifs";
		case 0x010f: return "Oldstyle Serifs - Miscellaneous";
		case 0x0200: return "Transitional Serifs";
		case 0x0201: return "Transitional Serifs - Direct Line"
		case 0x0202: return "Transitional Serifs - Script";
		case 0x020e: return "Transitional Serifs";
		case 0x020f: return "Transitional Serifs - Miscellaneous";
		case 0x0300: return "Modern Serifs";
		case 0x0301: return "Modern Serifs - Italian";
		case 0x0302: return "Modern Serifs - Script";
		case 0x030e: return "Modern Serifs";
		case 0x030f: return "Modern Serifs - Miscellaneous";
		case 0x0400: return "Clarendon Serifs";
		case 0x0401: return "Clarendon Serifs - Clarendon";
		case 0x0402: return "Clarendon Serifs - Modern";
		case 0x0403: return "Clarendon Serifs - Traditional";
		case 0x0404: return "Clarendon Serifs - Newspaper";
		case 0x0405: return "Clarendon Serifs - Stub Serif";
		case 0x0406: return "Clarendon Serifs - Monotone";
		case 0x0407: return "Clarendon Serifs - Typewriter";
		case 0x040f: return "Clarendon Serifs - Miscellaneous";
		case 0x0500: return "Slab Serifs";
		case 0x0501: return "Slab Serifs - Monotone";
		case 0x0502: return "Slab Serifs - Humanist";
		case 0x0503: return "Slab Serifs - Geometric";
		case 0x0504: return "Slab Serifs - Swiss";
		case 0x0505: return "Slab Serifs - Typewriter";
		case 0x050f: return "Slab Serifs - Miscellaneous";
		case 0x0700: return "Freedom Serifs";
		case 0x0701: return "Freedom Serifs - Modern";
		case 0x070f: return "Freedom Serifs - Miscellaneous";
		case 0x0800: return "Sans Serif";
		case 0x0801: return "Sans Serif - IBM Neo-grotesque Gothic";
		case 0x0802: return "Sans Serif - Humanist";
		case 0x0803: return "Sans Serif - Low-x Round Geometric";
		case 0x0804: return "Sans Serif - High-x Round Geometric";
		case 0x0805: return "Sans Serif - Neo-grotesque Gothic";
		case 0x0806: return "Sans Serif - Modified Neo-grotesque Gothic";
		case 0x0809: return "Sans Serif - Typewriter Gothic";
		case 0x080a: return "Sans Serif - Matrix";
		case 0x080f: return "Miscellaneous";
		case 0x0900: return "Ornamentals";
		case 0x0901: return "Ornamentals - Engraver";
		case 0x0902: return "Ornamentals - Black Letter";
		case 0x0903: return "Ornamentals - Decorative";
		case 0x0904: return "Ornamentals - Three Dimensional";
		case 0x090f: return "Ornamentals - Miscellaneous";
		case 0x0a00: return "Scripts";
		case 0x0a01: return "Scripts - Uncial";
		case 0x0a02: return "Scripts - Brush Joined";
		case 0x0a03: return "Scripts - Formal Joined";
		case 0x0a04: return "Scripts - Monotone Joined";
		case 0x0a05: return "Scripts - Calligraphic";
		case 0x0a06: return "Scripts - Brush Unjoined";
		case 0x0a07: return "Scripts - Formal Unjoined";
		case 0x0a08: return "Scripts - Monotone Unjoined";
		case 0x0a0f: return "Scripts - Miscellaneous";
		case 0x0c00: return "Symbolic";
		case 0x0c03: return "Symbolic - Mixed Serif";
		case 0x0c06: return "Symbolic - Oldstyle Serif";
		case 0x0c07: return "Symbolic - Neo-grotesque Sans Serif";
		case 0x0c0f: return "Symbolic - Miscellaneous";
	}
};